{{- if .Values.gatewayConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rancher-mcp-proxy.fullname" . }}-roles
  labels:
    {{- include "rancher-mcp-proxy.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.gatewayConfig | nindent 4 }}
{{- end }}
